linkzone_core_admin_home:
    pattern: /
    defaults: { _controller: LinkZoneCoreAdminBundle:Default:index }

linkzone_core_admin_login:
    pattern: /login
    defaults: { _controller: LinkZoneCoreAdminBundle:Security:login }

linkzone_core_admin_login_check:
    pattern: /login_check
    defaults: { _controller: LinkZoneCoreAdminBundle:Security:check }
