linkzone_core_admin_login:
    pattern: /login
    defaults: { _controller: LinkZoneCoreAdminBundle:Security:login }

linkzone_core_admin_login_check:
    pattern: /login_check
    defaults: { _controller: LinkZoneCoreAdminBundle:Security:check }

linkzone_core_admin_logout:
    pattern: /logout
    defaults: { _controller: LinkZoneCoreAdminBundle:Security:logout }

linkzone_core_admin_home:
    pattern: /
    defaults: { _controller: LinkZoneCoreAdminBundle:Default:index }

linkzone_core_admin_manage_users:
    pattern: /manage/users
    defaults: { _controller: LinkZoneCoreAdminBundle:ManageUsers:list }

linkzone_core_admin_manage_user:
    pattern: /manage/user/{userId}
    defaults: { _controller: LinkZoneCoreAdminBundle:ManageUsers:specific }
    requirements:
        userId: \d+

linkzone_core_admin_manage_user_ajax_email:
    pattern: /ajax/manage/user/{userId}/email
    defaults: { _controller: LinkZoneCoreAdminBundle:ManageUsers:ajaxChangeUserEmail }
    requirements:
        userId: \d+

linkzone_core_admin_manage_user_ajax_billing:
    pattern: /ajax/manage/user/{userId}/billing
    defaults: { _controller: LinkZoneCoreAdminBundle:ManageUsers:ajaxChangeUserBilling }
    requirements:
        userId: \d+
