parameters:
    controller.listener.class: LinkZone\Core\AdminBundle\EventListener\ControllerListener

services:
    controller.listener:
        class: %controller.listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    link_zone_core_admin.menu_builder:
        class: LinkZone\Core\AdminBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]

    link_zone_core_admin.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: link_zone_core_admin.menu_builder
        factory_method: createMainMenu
        arguments: ["@request", "@translator"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: admin_main } # The alias is what is used to retrieve the menu
