parameters:
#    link_zone_core_admin.example.class: LinkZone\Core\AdminBundle\Example

services:
#    link_zone_core_admin.example:
#        class: %link_zone_core_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    link_zone_core_admin.menu_builder:
        class: LinkZone\Core\AdminBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]

    link_zone_core_admin.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: link_zone_core_admin.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu