parameters:
#    link_zone_core_admin.example.class: LinkZone\Core\AdminBundle\Example

services:
#    link_zone_core_admin.example:
#        class: %link_zone_core_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
