parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: null
    database_name: linkzone
    database_user: linkzone
    database_password: linkzone
    database_path: null

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    locale: ru
    secret: 0db21b7004b3128335b494ae132fa3edaaabf4c8

    linkzone_hostname: "linkzone.ru"
    activation_html_file_name_format: "%linkzone_hostname%_%s.html"
    activation_txt_file_name_format: "%linkzone_hostname%_%s.txt"

    default_date_format: "d.m.Y, H:i"

    default_link_html: "<a href='%%s'>%%s</a>"

    default_message_num_in_dialog: 10
    messages_to_load: 10

    verification_code_string_name: "verification-code"
