<?php

namespace LinkZone\Core\PublicBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use Doctrine\Common\Collections\ArrayCollection;

use FOS\UserBundle\Model\UserInterface;

/**
 * PlatformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends EntityRepository
{
    public function findAllReceivedForUser(UserInterface $user)
    {
        return new ArrayCollection($this->findBy(
                array('receiverUser' => $user),
                array('created' => "DESC")
        ));
    }

    public function findAllSentForUser(UserInterface $user)
    {
        return new ArrayCollection($this->findBy(
                array('senderUser' => $user),
                array('created' => "DESC")
        ));
    }
}
