LinkZone\Core\PublicBundle\Entity\PlatformTopic:
    type: entity
    table: platform_topics
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        description:
            type: string
            length: 255
        transKey:
            type: string
            length: 255
    oneToMany:
        platforms:
            targetEntity: LinkZone\Core\PublicBundle\Entity\Platform
            mappedBy: topic
    lifecycleCallbacks: {  }
