LinkZone\Core\PublicBundle\Entity\Platform:
    type: entity
    table: platforms.platforms
    repositoryClass: LinkZone\Core\PublicBundle\Repository\PlatformRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        url:
            type: string
            length: 1000
        description:
            type: string
            length: 2000
        status:
            type: string
            length: 100
        created:
            type: datetime
        hidden:
            type: boolean
        activationCode:
            type: string
            length: 24
            column: activation_code
    manyToOne:
        owner:
            targetEntity: LinkZone\Core\PublicBundle\Entity\User
            inversedBy: platforms
            joinColumn:
                name: user_id
                referencedColumnName: id
        topic:
            targetEntity: LinkZone\Core\PublicBundle\Entity\PlatformTopic
            inversedBy: platforms
            joinColumn:
                name: topic
                referencedColumnName: id
    oneToMany:
        requestsSent:
            targetEntity: LinkZone\Core\PublicBundle\Entity\Request
            mappedBy: senderPlatform
            orderBy:
                finished: DESC
                created: DESC
        requestsReceived:
            targetEntity: LinkZone\Core\PublicBundle\Entity\Request
            mappedBy: receiverPlatform
            orderBy:
                finished: DESC
                created: DESC

    lifecycleCallbacks: {  }
