LinkZone\Core\PublicBundle\Entity\Request:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        senderLink:
            type: string
            length: 255
            column: sender_link
        senderLinkText:
            type: string
            length: 255
            column: sender_link_text
        receiverLink:
            type: string
            length: 255
            column: receiver_link
        receiverLinkText:
            type: string
            length: 255
            column: receiver_link_text
        status:
            type: string
            length: 255
        created:
            type: datetime
        finished:
            type: datetime
    manyToOne:
        senderUser:
            targetEntity: LinkZone\Core\PublicBundle\Entity\User
            inversedBy: requestsSent
            joinColumn:
                name: sender_user
                referencedColumnName: id
        senderPlatform:
            targetEntity: LinkZone\Core\PublicBundle\Entity\Platform
            joinColumn:
                name: sender_platform
                referencedColumnName: id
        receiverUser:
            targetEntity: LinkZone\Core\PublicBundle\Entity\User
            inversedBy: requestsRecieved
            joinColumn:
                name: receiver_user
                referencedColumnName: id
        receiverPlatform:
            targetEntity: LinkZone\Core\PublicBundle\Entity\Platform
            joinColumn:
                name: receiver_platform
                referencedColumnName: id
    lifecycleCallbacks: {  }
