fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_registration_register_referral:
    pattern: /register/{referralValue}
    defaults: { _controller: FOSUserBundle:Registration:register }
    requirements:
        _method: GET

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

linkzone_core_public_home:
    pattern:  /
    defaults: { _controller: LinkZoneCorePublicBundle:Default:index }

linkzone_core_public_platforms:
    pattern: /platforms
    defaults: { _controller: LinkZoneCorePublicBundle:Platforms:index }

linkzone_core_public_platforms_ajax_platform_dialog:
    pattern: /ajax/platforms/dialog
    defaults: { _controller: LinkZoneCorePublicBundle:Platforms:ajaxPlatformDialog }
    requirements:
        _mehtod: GET

linkzone_core_public_platforms_ajax_add_platform:
    pattern: /ajax/platforms
    defaults: { _controller: LinkZoneCorePublicBundle:Platforms:ajaxAddPlatform }
    requirements:
        _method: POST

linkzone_core_public_platforms_ajax_edit_platform:
    pattern: /ajax/platforms/{platformId}
    defaults: { _controller: LinkZoneCorePublicBundle:Platforms:ajaxEditPlatform }
    requirements:
        _method:    POST
        platformId: \d+

linkzone_core_public_platforms_ajax_tags:
    pattern: /ajax/platforms/tags
    defaults: { _controller: LinkZoneCorePublicBundle:Platforms:ajaxGetTagsAutocomplete }
    requirements:
        _method: GET

linkzone_core_public_platforms_search:
    pattern: /platforms/search
    defaults: { _controller: LinkZoneCorePublicBundle:Platforms:search }
    requirements:
        _method: GET

linkzone_core_public_requests_exchange:
    pattern: /orders/for-exchange
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:exchange }
    requirements:
        _method: GET

linkzone_core_public_requests_in_progress:
    pattern: /orders/in-progress
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:inProgress }
    requirements:
        _method: GET

linkzone_core_public_requests_finished:
    pattern: /orders/finished
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:finished }
    requirements:
        _method: GET

linkzone_core_public_orders_ajax_send_order_dialog:
    pattern: /ajax/orders/send-order-dialog
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:ajaxSendOrderDialog }
    requirements:
        _method: GET

linkzone_core_public_orders_ajax_send_order:
    pattern: /ajax/orders/send-order
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:ajaxSendOrder }
    requirements:
        _method: POST

linkzone_core_public_orders_ajax_dialog_order_review:
    pattern: /ajax/dialog/orders/{orderId}/review
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:ajaxDialogReviewOrder }
    requirements:
        _method: GET
        orderId: \d+

linkzone_core_public_orders_ajax_approve_order:
    pattern: /ajax/orders/{orderId}/approve
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:ajaxApproveOrder }
    requirements:
        _method: POST
        orderId: \d+

linkzone_core_public_orders_ajax_deny_order:
    pattern: /ajax/orders/{orderId}/deny
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:ajaxDenyOrder }
    requirements:
        _method: POST
        orderId: \d+

linkzone_core_public_orders_ajax_set_receiver_link_locatin:
    pattern: /ajax/orders/{orderId}/receiver-link-location
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:ajaxReceiverLinkLocation }
    requirements:
        _method: POST
        orderId: \d+

linkzone_core_public_orders_ajax_set_sender_link_locatin:
    pattern: /ajax/orders/{orderId}/sender-link-location
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:ajaxSenderLinkLocation }
    requirements:
        _method: POST
        orderId: \d+

linkzone_core_public_orders_ajax_accept_order:
    pattern: /ajax/orders/{orderId}/accept-order
    defaults: { _controller: LinkZoneCorePublicBundle:Requests:ajaxAcceptOrder }
    requirements:
        _method: POST
        orderId: \d+

linkzone_core_public_messages:
    pattern: /messages
    defaults: { _controller: LinkZoneCorePublicBundle:Messages:index }
    requirements:
        _method: GET

linkzone_core_public_orders_dialog:
    pattern: /messagse/dialog/{dialogId}
    defaults: { _controller: LinkZoneCorePublicBundle:Messages:dialog }
    requirements:
        _method: GET
        dialogId: \d+

linkzone_core_public_orders_ajax_dialog_send_message:
    pattern: /ajax/dialog/send-message
    defaults: { _controller: LinkZoneCorePublicBundle:Messages:ajaxDialogSendMessage }
    requirements:
        _method: GET

linkzone_core_public_orders_ajax_send_message:
    pattern: /ajax/messages/send
    defaults: { _controller: LinkZoneCorePublicBundle:Messages:ajaxSendMessage }
    requirements:
        _method: POST

# partial templates
linkzone_core_public_partial_templates:
    resource: "@LinkZoneCorePublicBundle/Resources/config/routing/partial_templates.yml"
    prefix: /partials

# APi
linkzone_core_public_api_platforms:
    resource: "@LinkZoneCorePublicBundle/Resources/config/routing/api/platforms.yml"
    prefix: /api/platforms
