parameters:
#    link_zone_core_public.example.class: LinkZone\Core\PublicBundle\Example

services:
#    link_zone_core_public.example:
#        class: %link_zone_core_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
