LinkZone\Core\PublicBundle\Entity\Platform:
    properties:
        url:
            - NotBlank: ~
            - Url: ~
            - LinkZone\Core\PublicBundle\Validator\Constraints\SiteExists: ~
        description:
            - NotBlank: ~
            - Length:
                min: 200
                max: 2000