LinkZone\Core\PublicBundle\Entity\Platform:
    properties:
        url:
            - NotBlank: ~
            - Url: ~
            # - LinkZone\Core\PublicBundle\Validator\Constraints\SiteExists: { groups: [creation] }
        description:
            - NotBlank: ~
            - Length:
                min: 200
                max: 2000
LinkZone\Core\PublicBundle\Entity\Request:
    properties:
        senderLink:
            - NotBlank: { groups: [sender] }
            - Url:      { groups: [sender] }
            #- LinkZone\Core\PublicBundle\Validator\Constraints\SiteExists: { groups: [sender] }
        senderLinkText:
            - NotBlank: { groups: [sender] }
        receiverLink:
            - NotBlank: { groups: [receiver] }
            - Url:      { groups: [receiver] }
            #- LinkZone\Core\PublicBundle\Validator\Constraints\SiteExists: { groups: [receiver] }
        receiverLinkText:
            - NotBlank: { groups: [receiver] }
