linkzone_core_public_api_messages_all_dialogs:
    pattern: /dialogues/all
    defaults: { _controller: LinkZoneCorePublicBundle:Messages:apiDialogList }
    methods: [GET]

linkzone_core_public_api_messages_dialog:
    pattern: /dialogues/{dialogId}
    defaults: { _controller: LinkZoneCorePublicBundle:Messages:apiDialog }
    methods: [GET]

linkzone_core_public_api_messages_send:
    pattern: /send
    defaults: { _controller: LinkZoneCorePublicBundle:Messages:apiSendMessage }
    methods: [POST]

linkzone_core_public_api_messages_all:
    pattern: /dialogues/{dialogId}/messages/all
    defaults:
      _controller: LinkZoneCorePublicBundle:Messages:apiListDialogMessages
    methods: [GET]
