linkzone_core_public_partial_templates_login:
    pattern: /default/login.html
    defaults: { _controller: LinkZoneCorePublicBundle:Security:loginPartial }
    requirements:
        _method: GET

# We need this separate route to not interfere with 'linkzone_core_public_partial_templates_platform_dialog' route on 'confirm' action
linkzone_core_public_partial_templates_confirm_platform_dialog:
    pattern: /platforms/confirm_dialog.html
    defaults: { _controller: LinkZoneCorePublicBundle:Default:partials, controller: 'platforms', partial: 'confirm_dialog' }
    requirements:
        _method: GET

linkzone_core_public_partial_templates_platform_dialog:
    pattern: /platforms/{action}_dialog.html
    defaults: { _controller: LinkZoneCorePublicBundle:Platforms:ajaxPlatformDialog }
    requirements:
        _method: GET

linkzone_core_public_partial_templates_platform_search_filter:
    pattern: /platforms/search-filter.html
    defaults: { _controller: LinkZoneCorePublicBundle:Platforms:ajaxSearchFilterPartial }
    requirements:
        _method: GET

linkzone_core_public_partial_templates_common:
    pattern: /{controller}/{partial}.html
    defaults: { _controller: LinkZoneCorePublicBundle:Default:partials }
    requirements:
        _method: GET
