LinkZone\Core\AdminBundle\Entity\LogPlatformStatusChangesEntry:
    type: entity
    table: log_platform_status_changes
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        platformId:
            type: integer
        fromStatus:
            type: string
            length: '100'
        toStatus:
            type: string
            length: '100'
        date:
            type: datetime
        whoChanged:
            type: string
            length: 255
        reason:
            type: string
            length: 255
    lifecycleCallbacks: {  }
