LinkZone\Core\AdminBundle\Entity\LogStatusChangesEntry:
    type: entity
    table: log_status_changes
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        userId:
            type: integer
            column: user_id
        fromStatus:
            type: string
            length: 100
            column: from_status
        toStatus:
            type: string
            length: 100
            column: to_status
        date:
            type: datetime
        whoChanged:
            type: string
            length: 255
            column: who_changed
        reason:
            type: string
            length: 255
    lifecycleCallbacks: {  }
